version: 0.2

phases:
  build:
    commands:
      - cargo test
      - cargo build --release --package fuzzy_cli

artifacts:
  files:
    - target/release/fuzzy_cli
  discard-paths: yes

cache:
  paths:
    - $HOME/.cargo/registry/**/*
